### ISSUE TITLE
Duda con la lectura de ficheros .json

### ISSUE THREAD

**Issue by aglezg** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101321219#1]
Hola buenas tardes,

Implementando la función `readFileSync` que nos incluye `fs` me ha saltado la siguiente duda.

https://github.com/ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101321219/blob/1335555d45629e8a90d0b353f2d2a576cfb1c3f4/src/noteMagenement.ts#L34-L41

En la línea 38 del trozo de código adjunto convierto la lectura en objeto mediante `JSON.parse`. Seguidamente, interpreto que lo leído es un objeto de la clase `Note` (por lo que incluye un titulo, un cuerpo y un color) y  devuelvo la cadena a imprimir mediante otra clase `NotePrinter`.

No obstante, podría suceder que leyera un fichero '.json' que no tenga la estructura que se corresponde con las estructura de una nota, por lo que podría no tener los campos anteriormente mencionados. ¿Hay alguna forma de comprobar que el objeto leído sea un objeto de tipo 'Note'? He probado a utilizar `instanceof` pero no cumple la condición del `if`.

Gracias de antemano.

Un saludo,

Adrián

@esegredo

**Comment by esegredo** [comment]
Hola Adrián, buenos días.

En ningún caso, lo que leas será una instancia de una clase, aunque si un objeto. Si quieres construir una instancia de una clase, tendrás que invocar al constructor de la clase con los datos del objeto JSON que has parseado desde el fichero.

En ese caso, si que podrás utilizar instanceof. Ahora no puedes usarlo, precisamente, por lo que te he comentado. Todos los objetos devuelven 'object' cuando se usa instanceof.

Otra opción, si no quieres obtener una instancia de la clase, es utilizar el operador in, que comprueba que cierta propiedad existe en el objeto que has leído. Algo como:

```typescript
if ('title' in myNote) {
...
}
```

Espero haberme explicado.

Saludos.
